### ISSUE TITLE
Two points

### ISSUE THREAD

**Issue by Yoak3n** [superman66/wakatime-sync#23]
1. I added a trigger named "work_dispatch" in the schedule.yml to run the workflow manually through reading [Manually running a workflow - GitHub Docs](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).After that there will be a run manually button of the workflow otherwise there is nothing.Or We should edit REAM.md to explain clearly how to run manually .Well, maybe I'm too new.
![image.png](https://yoaken-1316330335.cos.ap-chongqing.myqcloud.com/markdownPic/202301051550715.png)
2. I get a warning when finishing running the workflow that says :"update-gist:Node.js 12 actions are deprecated. For more information see:https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: superman66/wakatime-sync@master". I have updated node12 to 16 in my file action.yml. It doesn't matter and may becomes a bug but just a try .
![image.png](https://yoaken-1316330335.cos.ap-chongqing.myqcloud.com/markdownPic/202301051548710.png)

**Comment by ChenDaqian** [comment]
I also encountered this problem and need to modify the schedule.yml file. Add **workflow_dispatch**:
For example：
```yml
name: Update gist with WakaTime summary
on:
schedule:
- cron: '30 13 * * *'
workflow_dispatch:
jobs:
update-gist:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@master
- name: Update gist
uses: ChenDaqian/wakatime-sync@master
env:
GH_TOKEN: ${{ secrets.GH_TOKEN }}
GIST_ID: ${{ secrets.GIST_ID}}
WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
SCU_KEY: ${{ secrets.SCU_KEY }}
```
